### ISSUE TITLE
Human-robot collaborative object transfer using human motion prediction based on Dynamic Movement Primitives

### ISSUE THREAD

**Issue by Xmasterc** [Slifer64/DMP_KF#1]
Hi Antonis, I was recently reading your article on EKF and DMP, in the EKF content, you don't seem to give the equation of state, so you use external forces to analyze the desired state, can I understand that. In addition, I learned your matlab program, the content of the program and the article are very different, no offense, I have some doubts, but your article still benefits me a lot, thank you very much

**Comment by Slifer64** [comment]
The state equation is given by (9), the measurement equation by (10) and the corresponding EKF observer, by (19)-(20)
Regarding your comment about the code, I suppose you refer to the 'master' branch. Of course they are different! I don't state anywhere that this is the code for the paper :P ... The 'master' branch contains other approaches I was experimenting with, prior to the paper. The code that is consistent with the paper is at the 'ekf_disc' branch. It's been a long time now, and I cannot recall if I have made any further changes, after the publication (I suppose I haven't). Anyways, you can see some examples if you like, e.g. you could run 'sim_DMP_EKF_disc.m' from the folder 'DMP_KF/matlab/DMP_EKF'. Or you can even inspect the c++ code that was used in the experiments that are documented in the paper. For instance you can refer to 'void DMP_EKF_Controller::execute()' from the file 'DMP_EKF_Controller.cpp'. Finally, keep in mind that I haven't committed in any way in providing support or documentation for this repository and unfortunately I don't have time to do so. You are welcome to examine the code (and if you use it in a project of yours, referring to my publication or providing credit to my repo would be appreciated :) ), but I cannot promise that I will have time to go into details...
